### ISSUE TITLE
How to keep the clock ticking in a background tab?

### ISSUE THREAD

**Issue by devinmooers** [sebpiq/WAAClock#11]
So I'm making a generative instrument web app, and I'd like for it to work in a background tab, but modern browsers clamp setInterval to 1000ms minimum. I thought of using web workers, but they don't have access to AudioContext, and therefore no WAAClock ability. Any way you can see around this? Any way to keep the clock ticking on-time when it's in a background tab?

**Comment by sebpiq** [comment]
Hmm that's a good point, I actually chose not to use a `setInterval` for that very reason, and use a `ProcessorNode` instead. But in order to not block the audio process I use this hack https://github.com/sebpiq/WAAClock/blob/2b782db898a666e0ad6fc49b9e96428da309c42f/lib/WAAClock.js#L140 i.e. execute the whole code in a `setTimeout(0)`, so on next tick. However this is quite dumb as it totally defeats the purpose of not using a `setInterval`, and also blocks when changing tab ... Maybe using `setImmediate` instead would do the trick!? I have to test how it behaves in the background ... otherwise just removing this hack and running among the rest of the audio.

**Comment by sebpiq** [comment]
If you could try again now? Using `setImmediate` should have fixed it. At least for me it seems to work better now.

**Comment by devinmooers** [comment]
Genius! Works perfectly now. Thanks for the snappy fix, really appreciate it!

**Comment by sebpiq** [comment]
:)
