### ISSUE TITLE
Events will be scheduled if deadline is set to 0 and clock has not been started

### ISSUE THREAD

**Issue by zya** [sebpiq/WAAClock#14]
````js
clock.callbackAtTime(function () {
    //do stuff
  }, 0).repeat(2);
````
and I have not event called `clock.start()`. 

The event will be scheduled and will run only once before stopping.

**Comment by zya** [comment]
I didn't have permission to push my changes but changing the line below fixed it for me.

https://github.com/sebpiq/WAAClock/blob/master/lib/WAAClock.js#L71 

to 

````js
  if (this.clock.context.currentTime >= this._earliestTime && this.clock._started) {
    this._execute()
  
  } else if (this.clock._hasEvent(this)) {
    this.clock._removeEvent(this)
    this.clock._insertEvent(this)
  
  } else this.clock._insertEvent(this)
````

**Comment by sebpiq** [comment]
Ok, this should be fixed now :) thanks for reporting!

**Comment by zya** [comment]
@sebpiq  I'd like to contribute if you could add me as a collaborator btw.

**Comment by sebpiq** [comment]
@zya that would be great! The standard way of contributing though is that you would fork the library, make your changes, push them to github and then create a pull request. That allows me to control what comes in, possibly edit the changes, in order to make sure that the code stays clean, the style consistent, etc ... If you have questions about this process, don't hesitate to contact me on my email!
